# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

#    resolvers:
#        download_resolver:
#            web_path:
#                web_root: "%kernel.project_dir%/public/"
#                cache_prefix: "%article_uploads%"

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: "%article_uploads%"

    filter_sets:
        download:
            cache: default
            quality: 90
            filters:
                thumbnail:
                    size: [ 300, 300 ]
                    mode: outbound
